[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/players"
  to = "/.netlify/functions/players"
  status = 200

[[redirects]]
  from = "/images/*"
  to = "/.netlify/functions/players/images/:splat"
  status = 200
